### PR TITLE
CMake: add  yaDSKY2

### PR DESCRIPTION
**Pull request by scivision**
add yaDSKY2 target for CMake. tested on Ubuntu 20.04 to build and open partial GUI

Note: I [uncommented rfopen declaration](https://github.com/virtualagc/virtualagc/compare/master...scivision:cmake_dsky2?expand=1#diff-c0054939c01f0b7949cfb62d96410c30R546) hopefully that is not disruptive or incorrect

### CODE REVIEW

**Comment by rburkey2005** [comment]
Curious.  I wonder why I commented it out?  Still, it seems safe enough.

**Comment by Thymo-** [comment]
For some reason it was declared here already: https://github.com/virtualagc/virtualagc/blob/master/yaAGC/agc_engine_init.c#L107

**Comment by rburkey2005** [comment]
And in lots of other .c files as well. 

Well, it's tough trying to reconstruct the thought process.

**Comment by scivision** [comment]
It could be that since the Makefiles specify some things repeatedly, the more sparse specifications of CMake is uncovering this slight issue. I didn't do a "clean" rebuild until I noticed the CI failed, and then I saw the missing include <stdioh> in #1121

**Pull request merged**
