### PR TITLE
Reconstructed Luminary 178

### PR DESCRIPTION
**Pull request by thewonderidiot**
After a month of work as described in #1093, I've finally (somewhat unexpectedly) finished reconstructing Luminary 178! It turns out the Densmore Luminary memos are very good, and describe essentially all of the changes well enough to sort out when they happened. I've tested it for basic functionality in standalone yaAGC, and @indy91 created a padload for it and performed a test landing using the NASSP Apollo 14 Pre-PDI scenario. It passed the landing with flying colors!
image

Only six lines of code had to be guessed/written anew; the other changes were all either present in one of Luminary 131, Zerlina 56, or Luminary 210, _or_ described well enough in the memos that only one code option was possible.

The first two of the six "new" lines are in P63START4 (`CAF ONE; TS LRPOS`). The flowcharts showed the location of this code, and that LRPOS was initialized with 1. The naive implementation here seems to be correct.

The remaining four are a different implementation of the remode check in RRDESEND. The naive change to the flag checking code in Luminary 210 didn't work. However, changing to another pattern frequently used to test flags gave the right sum (with the right number of words in the bank), so I'm pretty sure it's correct.

Since this reconstruction has gone so much further than all of the others so far (which have only been a revision or two away from something we had), there's a lot more room for cosmetic errors in this. Specifically, the exact location of erasable definitions (i.e., the order that they are presented in ERASABLE ASSIGNMENTS) and comments throughout are practically guaranteed to have errors. For comments in particular, sometimes the Luminary memos simply say things like "Comments were updated for E3", giving an entire bank in which comments may have changed. I've done my best to pick comments from the closest listing for each chunk of code, but there are definitely places I have it wrong.

All of this is cosmetic though; after having gone through everything I'm quite confident that the code itself and the binaries produced are correct. But to build more confidence, I'm planning on taking this and pushing backwards to Luminary 173, and maybe/hopefully 163. Each of those is described by a single memo instead of many, so it should be a much easier job.

### CODE REVIEW

**Comment by rburkey2005** [comment]
@thewonderidiot A masterpiece, Mike, truly.  Awesome work. I'd say it's worthy of being on a résumé, except that that would minimize it.  I'd say it's worthy of an award, except (excepting Margaret Hamilton) nobody hands out awards for the AGC.  Excuse my gushing.  Mainly, it's been a sore spot with me that we've had (more or less) all of the flown Luminary versions except 178, and now you've filled that gap.

@indy91 And thanks, Nik. Having it flown in the sim is the final icing on the cake.

**Comment by indy91** [comment]
Yes, Mike did an outstanding job! What I had to do was quite simple really. Between Luminary 1D and 1E the padloaded parameters and their addresses changed almost not at all, so I took an Apollo 14 pre PDI scenario I had lying around, changed the address of just a single padloaded parameter and ran the scenario. The AGC complained just a little bit that I had suddenly given it another rope (41203 alarm), but after that it worked flawlessly.

**Comment by rburkey2005** [comment]
@indy91 I'm in the process of writing it all up for the website, and there was a lovely description there before of how you had adapted Luminary 210's ephemeris to fly simulated Apollo 14 landings.  I almost regret having to remove it to make way for the updated situation.

**Comment by indy91** [comment]
@rburkey2005 Yeah, I felt the same way when I removed the modified rope from our repository. I saved a backup of it though, it will definitely not be lost or forgotten that it worked great for flying Apollo 14!

**Comment by thewonderidiot** [comment]
Haha, thanks a lot! :smile: To be honest, I'm still a bit shocked that it actually came together. My first approach of removing all of the Zerlina-specific stuff from Zerlina and then only using the Luminary 179 through Luminary 183 memos to back out changes ended up failing pretty badly... I think I still had 34 out of 36 banks wrong after that. That's what pushed me in the direction of just doing a 3-way diff of every section and trying to pin every single difference I saw on a particular revision. And for that I think I had to go through over a thousand pages before I had more than 4 banks right at the same time!

Only one flown Luminary (LM131 Rev 1) remains to be reconstructed... but I'm going to do Luminary 173 and 163 first, I think, while I'm still in the 1D mindset.

**Pull request merged**
