### PR TITLE
Update to 2004929-

### PR DESCRIPTION
**Pull request by HeliumHead**

### CODE REVIEW

**Comment by rburkey2005** [comment]
@HeliumHead I'm a bit confused what this is.  An accident?

**Comment by ohommes** [comment]
I assume he accidentally deleted the folders but you cannot accept the
patch as is with all the agc deletes.

**Comment by rburkey2005** [comment]
@ohommes I'm not sure you're right about that.  The deletions (Zerlina, Artemis072, ...) are removal of software from the "mechanical" branch.  And I was the one who deleted them, back in 2019.  HeliumHead's commit is to the mechanical branch only, and I think those changes are confined to the .stp and .md files in the mechanical branch, as they should be.

I'll have to look at it in more detail to be sure, though, because I was confused when I made my earlier comment.  The only changes I saw when I made that comment had been made long ago by me or by Manoel, and I couldn't see any of HeliumHead's changes at all.  I didn't see the [link that revealed those _new_ changes](https://github.com/virtualagc/virtualagc/pull/1141/files/50c81508bae0a95e1f7061bb923c8679394f06f9..HEAD) until just now, so I've only skimmed them.  

I don't understand why all of my and Manoel's old changes are showing up now.  Perhaps HeliumHead's last pull was a very long time ago, before those Manoel and my changes had been made.

@ManoDaSilva But I think that Manoel should weigh in on HeliumHead's changes.  I'm not confident in my own ability to vet them.

**Comment by ManoDaSilva** [comment]
I'm a little bit lost, I'm seeing all my commits show up now as coming from HeliumHead's, but I don't see what he's adding. GitHub shows only part of the 3000+(!) files edited...

**Comment by rburkey2005** [comment]
Thanks! I'm going to delete it.

@HeliumHead:  As you can see, we're confused about what you've done here.  If you've made some actual changes (as opposed to merely accidentally generating and then closing a pull request), to keep us from being confused I'd suggest that you:

- Make a clean pull or clone from the "mechanical" branch of the repository, in order to have everything up-to-date on your local system with respect to the current state.
- Only _after_ you've done that, make your changes to the .stp files and/or .md files.
- Generate a clean pull request.

**Comment by HeliumHead** [comment]
I was trying to update the 2004929- stp file, but I didn't know what I was doing. Sorry for all the trouble I caused!

**Comment by rburkey2005** [comment]
No problem!  I just accidentally deleted the entire branch (but have hopefully now restored it), so I can't point fingers.  :smile:

**Comment by rburkey2005** [comment]
**Note to self**:  In an aborted pull request, when GitHub offers the opportunity to "delete branch", it means deleteing the _entire branch_, not the pull request.  So don't do it!  It's annoying.

**Pull request closed without merging**
