### PR TITLE
Upgrade dependency wasi-sdk for WebAssembly builds

### PR DESCRIPTION
**Pull request by michaelfranzl**
This is the pull request that should be merged together with https://github.com/virtualagc/virtualagc/pull/1182

To make the WebAssembly build more simple, I've made the optimization steps optional and simply mentioned them in the text.

### CODE REVIEW

**Comment by rburkey2005** [comment]
@michaelfranzl Thanks!  I've merged both.

**Comment by rburkey2005** [comment]
@michaelfranzl I was able to follow the build instructions all right, but the instructions for how to run it defeated me.

I got as far as 
<pre>
npm ci
cd demo
npm ci
</pre>
in the README.md file.  The first `npm ci` worked okay, but the `npm ci` in the demo/ folder did not.  It gave the error message
<pre>
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR! 
npm ERR! Invalid: lock file's webagc@1.1.0 does not satisfy webagc@
npm ERR! Missing: webagc@ from lock file
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rburkey/.npm/_logs/2022-09-24T17_40_12_972Z-debug-0.log
</pre>

I then tried `npm install` as it suggested, but that gave me the following error message:
<pre>
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/webdsky/-/webdsky-1.1.2.tgz - Not found
npm ERR! 404 
npm ERR! 404  'webdsky@https://registry.npmjs.org/webdsky/-/webdsky-1.1.2.tgz' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rburkey/.npm/_logs/2022-09-24T17_40_25_061Z-debug-0.log
</pre>

I'm afraid I don't have enough knowledge &mdash; i.e., not >0 &mdash; to proceed.

Thoughts?

**Comment by michaelfranzl** [comment]
@rburkey2005 Sorry for the inconvenience. I broke it quite some time ago (there was a typo and a missing dependency). I fixed it. Please try again on an up to date `main` branch.

**Comment by rburkey2005** [comment]
@michaelfranzl Yes, that fixed it, thanks!  

And very nice, too.  I'm ashamed to say that I had forgotten a lot since the last time I looked at it, but it's a very impressive representation.   Good work!

I do have a couple of comments, if you don't mind some minor quibbles:

1. It gives me a warning message: "This browser is too old. The application may not run correctly, or at all. Requiring at least Firefox version 78 or Chrome version 89."  But as it happens, I'm running Firefox 104 and Chrome 105, so apparently it's not detecting browser versions correctly.
2. The arrangement is a little confusing, because the first thing that is logical (for me at least) to try is to start using the "DSKY key input" field in the "DISPLAY AND KEYBOARD (DSKY) OF THE AGC" section ... which of course does essentially nothing since there's no AGC software loaded by default.  It might be better if one or the other of the AGC programs were loaded by default.  Or if the "DISPLAY AND KEYBOARD (DSKY) OF THE AGC" section were moved below the "AGC SOFTWARE" section, so that it was more-immediately obvious that you have to choose the AGC software _first_.
3. And I think it would be better if the DSKY were moved to the right-hand side rather than being the left-hand side.  As it is now, it's a little confusing because of the DSKY's relationship to the "DISPLAY AND KEYBOARD (DSKY) OF THE AGC" heading:  It makes it appear (to my eye) as though "AGC SOFTWARE" is a sub-section of "DISPLAY AND KEYBOARD (DSKY) OF THE AGC" rather than being on an equal level with it.

**Comment by michaelfranzl** [comment]
Thank you for your improvement suggestions. I'm going to apply them as far as this is possible in today's development state of webAGC, as I've been developing it over the last year. The interface of the web application has changed almost completely and the browser requirements have changed too. This is not published yet, as I'd like to polish the code before I do, but I hope it will in the next few weeks. After which I'd be very happy to hear additional feature requests, improvement suggestions and bug reports.

**Pull request merged**
