### PR TITLE
Reconstruction of Manche72 revision 3

### PR DESCRIPTION
**Pull request by thewonderidiot**
Here's a reconstruction of Manche72 revision 3, with the changes described in #1180. I think this solution is a likely one, but the addition to bank 11 is so large (12 words!) that I would be a bit surprised if there weren't alternate implementations that lead to the same banksum. So, as with Comanche 72, I think there is ambiguity here that we won't be able to rid ourselves of until we find more sources.

### CODE REVIEW

**Comment by thewonderidiot** [comment]
@indy91 has done a little bit of testing of this one in NASSP, with more to come soon. The parts he's checked out so far have worked. :crossed_fingers:

**Comment by rburkey2005** [comment]
Okay, great!  I'll write up both Comanche 72 and Mache72 rev 3 with those provisions.

I'm wondering, though ... are you so confident that there weren't workable alternate instruction-sequences on _prior_ revisions?  It always seemed to be a possibility before, but I don't recall it being significant enough to have extra attention called to it.  So is the risk of it really bigger now with 72 and 72/3, or is it that you've become more sensitized to the possibility?

**Comment by thewonderidiot** [comment]
My general feeling is that the more code we have to write ourselves, the more likely we are to get it wrong. A _lot_ of the reconstructions we've done in the past have involved writing essentially no new code whatsoever -- for those, we essentially just selectively copy-pasted original code from other revisions. Some of them have required new code, but only a small handful of instructions, in which the number of possible solutions that achieve the same banksum is very small. Comanche 72 required adding new code where e.g. we didn't know the placement of an INHINT from a later rope, and didn't know the exact value of a constant we had to add. And this one just requires so many new words that the solution space is very large.

**Comment by rburkey2005** [comment]
More now, got it!  Thanks.

**Pull request merged**
