### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by shirriff**
More typos in YUL code.

### CODE REVIEW

**Comment by rburkey2005** [comment]
@shirriff Great job, Ken, thanks!  If you're going to keep submitting these patches (please do!), then I'm going to do what I did with the last one:  let it sit here a few days for @jimlawton to look at, and then approve it myself if not.  I wanted to mention that in case you think your patches are being neglected.

By the way, are you intending to _do_ something with this code after making all these corrections?  Just curiosity.  If you aren't, or don't want to say, no problem.

**Comment by shirriff** [comment]
Hi Ron! I'm trying to get the YUL code running, so I'm fixing the typos I encounter along the way.

**Comment by rburkey2005** [comment]
Cool!  You mean you have a Honeywell 800 or an emulator for it?

**Comment by shirriff** [comment]
I'll have an emulator once I write one :-)

**Comment by rburkey2005** [comment]
Ambitious much?  :smile:  Sounds good!

**Comment by jimlawton** [comment]
Sorry Ken, I was on vacation.

**Comment by shirriff** [comment]
No worries, Jim. I hope you had a good vacation.

**Pull request merged**
