### PR TITLE
Transcribe DISPLAY INTERFACE ROUTINES (pp. 1338-1370)

### PR DESCRIPTION
**Pull request by kociak1984**
This was quite a challenge to be honest. Took me around 4 hours.

### CODE REVIEW

**Comment by kociak1984** [comment]
Oh, date should be today, not tomorrow.. (is: 2016-12-08, should be 2016-12-07)
But to be honest - who cares :P

**Comment by rburkey2005** [comment]
@kociak1984 There's no doubt that this stuff can be quite a challenge, particularly the more care you apply to it, which is why we really appreciate the effort!

**Comment by kociak1984** [comment]
Trying to do my best.

**Comment by thewonderidiot** [comment]
Indeed, thanks a bunch for the help! :)

**Pull request merged**
