### PR TITLE
Sundance 306ish

### PR DESCRIPTION
**Pull request by thewonderidiot**
Here is my current best guess for what Sundance 306 looked like. All of the changes I made are documented and argued (more or less successfully) in #1125. It's close enough, at least, that the six module B6 banks all assemble to exactly match the 306 module dump, down to the bugger word. @indy91 is test flying this in NASSP right now, now using the actual flown padload. :smile:

### CODE REVIEW

**Comment by rburkey2005** [comment]
I want to wait to see what Nik comes up before doing anything with it, given the lack of other means of checking validity.  But in anticipation of that, great job! Sent on my Virgin Mobile Samsung Galaxy S® 5

-------- Original message --------

**Comment by rburkey2005** [comment]
On second thought, given the delay involved, I guess it makes more sense to go ahead and merge it (which I'm doing), and then to just write it up in a way that makes clear that it hasn't been successfully test-flown yet.

**Comment by thewonderidiot** [comment]
Okay! Niklas is also updating the NASSP checklists this time through, which is why it's taking a bit longer. He got up to undocking today and is hoping to have the mission fully completed by the end of the weekend.

**Comment by rburkey2005** [comment]
No problem. I can't complain.  I'm just happy it's being done at all.Sent on my Virgin Mobile Samsung Galaxy S® 5

-------- Original message --------

**Comment by indy91** [comment]
I'm not expecting any issues with Sundance306ish, but of course I have to test everything with it before I can commit it to be used by everyone in NASSP.

**Comment by rburkey2005** [comment]
@indy91 Understood.  I have the same problem.  Not in terms of commits, of course, but in terms of endorsing Sundance306ish vs SundanceXXX in my website write-up.  At any rate, there's no pressure.  The more effort you want to spend on it, the better as far as I'm concerned.  :smile:

**Comment by indy91** [comment]
I have flown the full Apollo 9 mission (at least the parts with the LM) using Sundance306ish and it performed very well! Apollo 9 is a good workout for Sundance, lots of things being tested. And it's now used for Apollo 9 in NASSP.

**Comment by rburkey2005** [comment]
Yay!  Great job, thanks!

**Pull request merged**
